# Worksheet 04

Name: Woo Hyeon Her <br>
UID: U88838753

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

<b>d</b> : dimensional space <br>
<b>p</b>: the tune distance (p=1 Manhattan distance, p=2 Euclidian distance)

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

For Euclidean distance, p is equal to 2. And it can measure diagonally. For Manhttan distance, p is equal to 1. It cannot measure diagonally, meaning it only has up down and left right. 

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

As p approaches a very large number, or infinity, I think the distance would approache 0. However, it would not reach 0 because having 0 distance does not make sense.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

It is not a distance function when p is less than 1. When p is less than 1, the triangle inequality of d(A, B) + d(B, C) >= d(A, C) cannot be satisfied. Distance from A to C would be larger than the sum of distance from A to B and B to C. 

e) when would you use cosine similarity over the euclidan distance?

When direction matters more than magnitude, you use cosine similarity over the euclidian distance.

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard distance account for the size of the intersection, which the manhattan distance does not.

#### Part 2

Consider the following two sentences:

In [8]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [9]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [10]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Bob', 'my', 'is', 'hello', 'name', 'Alice']
[0, 1, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [11]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [12]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)


['Bob', 'Claude', 'my', 'is', 'hello', 'name', 'Alice', 'hi']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [13]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 0, 1, 1, 1, 1, 1, 0]
[1, 0, 1, 1, 1, 1, 0, 0]
[0, 1, 1, 1, 0, 1, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [14]:
def minkowski(x, y, p):
    if len(x) != len(y):
        raise RuntimeError("x and y must be of the same dimension")
    res = 0
    for i in range(len(x)):
        res += abs(x[i] - y[i]) ** p
    return res ** (1 / p)

print(minkowski([0, 0], [1, 1], 2))
print(minkowski([0, 0], [1, 1], 1))

1.4142135623730951
2.0


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [16]:
s1 = "hi Alice"
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"

all_words = list(set([item for x in corpus for item in x.split()]))
matrix = []
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
v4 = [1 if x in s4 else 0 for x in all_words]
v5 = [1 if x in s5 else 0 for x in all_words]
matrix.append(v1)
matrix.append(v2)
matrix.append(v3)
matrix.append(v4)
matrix.append(v5)

print(matrix)

['Bob', 'Claude', 'my', 'is', 'hello', 'name', 'Alice', 'hi']
[[0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 1, 0, 0, 0], [1, 1, 1, 1, 0, 1, 0, 0], [0, 1, 1, 1, 0, 1, 1, 1], [1, 0, 0, 0, 1, 0, 0, 0]]


e) How many rows and columns does this matrix have?

This matrix has 5 rows and 8 columns. Each row represents a document and each column represents a word. The value of each cell is 1 if the word is in the document and 0 otherwise. 

f) When using the Manhattan distance, which two sentences are the most similar?

In [22]:
for i in range(len(matrix)):
    for j in range(i + 1, len(matrix)):
        print("distance between", i, "and", j, ":", minkowski(matrix[i], matrix[j], 1))

distance between 0 and 1 : 4.0
distance between 0 and 2 : 7.0
distance between 0 and 3 : 4.0
distance between 0 and 4 : 4.0
distance between 1 and 2 : 5.0
distance between 1 and 3 : 6.0
distance between 1 and 4 : 2.0
distance between 2 and 3 : 3.0
distance between 2 and 4 : 5.0
distance between 3 and 4 : 8.0


As seen above, the two most similar sentences are s2 and s5. s2 = "hello Claude" and s5 = "hello Bob". Low number of Manhattan distance indicate the high similarity.



#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [11]:
import numpy as np


def pairwise_dist(graphs):
    n = len(graphs)
    distances = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            i_edge = set(zip(*np.where(graphs[i])))
            j_edge = set(zip(*np.where(graphs[j])))
            dist = len(i_edge - j_edge) + len(j_edge - i_edge)
            distances[i, j] = distances[j, i] = dist

    return distances

# Example usage:
graphs = [
    np.array([[0, 5, 0], 
              [1, 0, 1], 
              [0, 1, 0]]),  # Graph 1
    np.array([[0, 1, 1], 
              [1, 0, 0], 
              [1, 0, 0]]),  # Graph 2
    np.array([[0, 0, 1], 
              [0, 0, 1], 
              [1, 1, 0]])   # Graph 3
]
dist_matrix = pairwise_dist(graphs)
print("Pairwise distances:")
print(dist_matrix)


Pairwise distances:
[[0. 4. 4.]
 [4. 0. 4.]
 [4. 4. 0.]]
